
#' FPEMglobal.aux: Auxillary functions for FPEMglobal
#'
#' This package provides auxillary functions for reading and using the
#' results of models generated by the \pkg{FPEMglobal} package.
#'
#' @section Reading csv files:
#'
#' Almost everywhere, \code{\link[readr]{read_csv}} is used to read
#' csv files. This can result in lots of messages if you set argument
#' \code{verbose} to \code{TRUE}. To turn these off, set the options
#' \code{readr.show_progress} and \code{readr.show_col_types} to
#' \code{FALSE}.
#'
#' @docType package
#' @name FPEMglobal.aux

#' @importFrom magrittr %>%
NULL

#' @import dplyr
NULL

#' @import readr
NULL

#' @import tibble
NULL

#' @import tidyr
NULL



.onAttach <- function(libname, pkgname) {
    ## START-UP MESSAGE
    desc_fields <-
        c("Package", "Title", "Version",
          "Depends", "License", "Encoding", "Maintainer", "Built")
    pkg_desc <- packageDescription(pkgname)
    if("GitHubSHA1LastCommit" %in% names(pkg_desc))
        desc_fields <- c(desc_fields, "GitHubSHA1LastCommit")
    pkg_desc <- pkg_desc[desc_fields]
    pkg_desc <- paste(names(pkg_desc), pkg_desc, sep = ": ", collapse = "\n")
  packageStartupMessage(pkg_desc)
}
