#' FPEMglobal.aux: Auxillary functions for FPEMglobal
#'
#' This package provides auxillary functions for reading and using the
#' results of models generated by the \pkg{FPEMglobal} package.
#'
#' @section Reading csv files:
#'
#' Almost everywhere, \code{\link[readr]{read_csv}} is used to read
#' csv files. This will result in lots of messages if option
#' \code{"FPEMglobal.aux.verbose"} is \code{TRUE}. To turn these off,
#' either set option \code{"FPEMglobal.aux.verbose"} to \code{FALSE}
#' (the default), or set the options \code{"readr.show_progress"} and
#' \code{"readr.show_col_types"} to \code{FALSE}. Using \code{"FPEMglobal.aux.verbose"} will also
#' suppress all package-specific messages, whereas using the the latter will only
#' affect \pkg{readr} messages.
#'
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom magrittr %>%
## usethis namespace: end
NULL

#' @import dplyr
NULL

#' @import readr
NULL

#' @import tibble
NULL

#' @import tidyr
NULL
